#!/bin/sh

if [ -e /etc/pki/tls/cert.pem ]; then
  export SSL_CERT_FILE=/etc/pki/tls/cert.pem
elif [ -e /etc/ssl/cert.pem ]; then
  export SSL_CERT_FILE=/etc/ssl/cert.pem
else
  echo 'Failed to find cert.pem!'
fi

exec /app/bin/hexchat "$@"
