#!/bin/sh

# The cert file varies by distro...
# TODO: Test every distro ever made.
if [ -e /etc/pki/tls/cert.pem ]; then
  # Fedora
  export SSL_CERT_FILE=/etc/pki/tls/cert.pem
elif [ -e /etc/ssl/cert.pem ]; then
  # Arch
  export SSL_CERT_FILE=/etc/ssl/cert.pem
else
  echo 'Failed to find cert.pem!'
fi

own_name=$(basename "$0")
bin_name=${own_name::-8}
exec "/app/bin/$bin_name" "$@"
